#!/usr/bin/env node
import { readFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { createHash } from "node:crypto";
import { validateProvisioningRequestContract } from "./lib/provisioning_request_contract.mjs";

function printUsage() {
  console.log([
    "Usage: node scripts/validate_tenant_handoff_evidence.mjs --bundle <file> --state <file> [options]",
    "",
    "Required:",
    "  --bundle <file>        bundle.json generated by tenant:onboarding:bundle",
    "  --state <file>         handoff-state.json generated by tenant:handoff:update",
    "",
    "Options:",
    "  --request <file>       provisioning-request.json to validate and compare",
    "  --submission <file>    provisioning-submit-evidence.json to validate and compare",
    "  --apply-evidence <file> apply-request evidence JSON to validate and compare",
    "  --verify <file>        verify summary JSON to validate and compare",
    "  --help                 Show this help message",
  ].join("\n"));
}

function readArg(flag) {
  const index = process.argv.indexOf(flag);
  if (index === -1) {
    return null;
  }
  return process.argv[index + 1] ?? null;
}

function normalizeOptionalString(value) {
  if (typeof value !== "string") {
    return null;
  }
  const trimmed = value.trim();
  return trimmed === "" ? null : trimmed;
}

function isObject(value) {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}

function isIsoTimestamp(value) {
  return typeof value === "string" && value.trim() !== "" && Number.isFinite(Date.parse(value));
}

function sha256(text) {
  return createHash("sha256").update(text).digest("hex");
}

async function readJsonFile(pathArg, label) {
  const path = resolve(pathArg);
  const raw = await readFile(path, "utf8");
  let json;
  try {
    json = JSON.parse(raw);
  } catch (error) {
    throw new Error(`${label} is not valid JSON: ${error instanceof Error ? error.message : String(error)}`);
  }
  if (!isObject(json)) {
    throw new Error(`${label} must contain a JSON object`);
  }
  return { path, raw, json };
}

function expectString(container, key, errors, label = key) {
  const value = container[key];
  if (typeof value !== "string" || value.trim() === "") {
    errors.push(`${label} must be a non-empty string`);
    return null;
  }
  return value;
}

function expectBoolean(container, key, errors, label = key) {
  const value = container[key];
  if (typeof value !== "boolean") {
    errors.push(`${label} must be a boolean`);
    return null;
  }
  return value;
}

function expectNumber(container, key, errors, label = key) {
  const value = container[key];
  if (typeof value !== "number") {
    errors.push(`${label} must be a number`);
    return null;
  }
  return value;
}

function expectObject(container, key, errors, label = key) {
  const value = container[key];
  if (!isObject(value)) {
    errors.push(`${label} must be an object`);
    return null;
  }
  return value;
}

function expectArray(container, key, errors, label = key) {
  const value = container[key];
  if (!Array.isArray(value)) {
    errors.push(`${label} must be an array`);
    return null;
  }
  return value;
}

function expectNullableString(value, errors, label) {
  if (value !== null && value !== undefined && typeof value !== "string") {
    errors.push(`${label} must be null/undefined or a string`);
  }
}

function compareValue(actual, expected, errors, label) {
  if (JSON.stringify(actual) !== JSON.stringify(expected)) {
    errors.push(`${label} does not match the source evidence`);
  }
}

function summarizeBundle(bundleJson, bundlePath) {
  return {
    tenant_id: bundleJson.tenant_id ?? null,
    deploy_env: bundleJson.deploy_env ?? null,
    created_at: bundleJson.created_at ?? null,
    base_url: bundleJson.base_url ?? null,
    output_dir: bundleJson.output_dir ?? dirname(bundlePath),
    files: bundleJson.files ?? null,
    verification_artifacts: bundleJson.verification_artifacts ?? null,
    suggested_commands: bundleJson.suggested_commands ?? null,
  };
}

function summarizeRequest(requestFile) {
  const json = requestFile.json;
  return {
    path: requestFile.path,
    sha256: sha256(requestFile.raw),
    request_type: json.request_type ?? null,
    status: json.status ?? null,
    external_handoff: json.external_handoff ?? null,
    completion_criteria: json.completion_criteria ?? null,
    tenant: json.tenant ?? null,
    actions: Array.isArray(json.actions)
      ? json.actions.map((action) => ({
          action_id: action?.action_id ?? null,
          type: action?.type ?? null,
          required: action?.required ?? null,
          mode: action?.mode ?? null,
          evidence_path: action?.evidence_path ?? null,
        }))
      : null,
  };
}

function summarizeSubmission(submissionFile) {
  const json = submissionFile.json;
  const response = isObject(json.response) ? json.response : null;
  const endpoint = isObject(json.endpoint) ? json.endpoint : null;
  return {
    path: submissionFile.path,
    sha256: sha256(submissionFile.raw),
    ok: json.ok === true,
    submitted_at: json.submitted_at ?? null,
    dry_run: json.dry_run === true,
    endpoint: endpoint
      ? {
          url: endpoint.url ?? null,
          method: endpoint.method ?? null,
          timeout_ms: endpoint.timeout_ms ?? null,
        }
      : null,
    request: isObject(json.request) ? json.request.metadata ?? null : null,
    response: response
      ? {
          ok: response.ok ?? null,
          skipped: response.skipped ?? null,
          status: response.status ?? null,
          status_text: response.status_text ?? null,
          headers: response.headers ?? null,
        }
      : null,
  };
}

function summarizeApply(applyFile) {
  const json = applyFile.json;
  return {
    path: applyFile.path,
    sha256: sha256(applyFile.raw),
    ok: json.ok === true,
    mode: json.mode ?? null,
    base_url: json.base_url ?? null,
    tenant_id: json.tenant_id ?? null,
    started_at: json.started_at ?? null,
    completed_at: json.completed_at ?? null,
    duration_ms: json.duration_ms ?? null,
    request_type: json.request_type ?? null,
    schema_version: json.schema_version ?? null,
    summary: json.summary ?? null,
    error_count: Array.isArray(json.errors) ? json.errors.length : null,
  };
}

function summarizeVerify(verifyFile) {
  const json = verifyFile.json;
  const meta = isObject(json.meta) ? json.meta : null;
  const github = meta && isObject(meta.github) ? meta.github : null;
  return {
    path: verifyFile.path,
    sha256: sha256(verifyFile.raw),
    ok: json.ok === true,
    mode: json.mode ?? null,
    run_id: json.run_id ?? null,
    trace_id: json.trace_id ?? null,
    duration_ms: json.duration_ms ?? null,
    check_count: json.check_count ?? null,
    verification_output_path: json.verification_output_path ?? null,
    meta: meta
      ? {
          change_ref: meta.change_ref ?? null,
          github: github
            ? {
                repository: github.repository ?? null,
                workflow: github.workflow ?? null,
                run_id: github.run_id ?? null,
                run_attempt: github.run_attempt ?? null,
                ref: github.ref ?? null,
                sha: github.sha ?? null,
              }
            : null,
        }
      : null,
  };
}

async function main() {
  if (process.argv.includes("--help")) {
    printUsage();
    return;
  }

  const bundleArg = normalizeOptionalString(readArg("--bundle"));
  const stateArg = normalizeOptionalString(readArg("--state"));
  if (!bundleArg || !stateArg) {
    throw new Error(`--bundle and --state are required`);
  }

  const bundle = await readJsonFile(bundleArg, "bundle");
  const state = await readJsonFile(stateArg, "state");
  const request = normalizeOptionalString(readArg("--request"))
    ? await readJsonFile(readArg("--request"), "request")
    : null;
  const submission = normalizeOptionalString(readArg("--submission"))
    ? await readJsonFile(readArg("--submission"), "submission")
    : null;
  const applyEvidence = normalizeOptionalString(readArg("--apply-evidence"))
    ? await readJsonFile(readArg("--apply-evidence"), "apply evidence")
    : null;
  const verify = normalizeOptionalString(readArg("--verify"))
    ? await readJsonFile(readArg("--verify"), "verify summary")
    : null;

  const errors = [];

  if (bundle.json.ok !== true) {
    errors.push(`bundle.ok must be true`);
  }
  expectString(bundle.json, "tenant_id", errors, "bundle.tenant_id");
  if (!["staging", "production"].includes(bundle.json.deploy_env)) {
    errors.push(`bundle.deploy_env must be staging or production`);
  }
  if (!isIsoTimestamp(bundle.json.created_at)) {
    errors.push(`bundle.created_at must be an ISO timestamp`);
  }
  expectString(bundle.json, "base_url", errors, "bundle.base_url");
  expectString(bundle.json, "repo_root", errors, "bundle.repo_root");
  expectString(bundle.json, "output_dir", errors, "bundle.output_dir");
  expectObject(bundle.json, "files", errors, "bundle.files");
  expectObject(bundle.json, "verification_artifacts", errors, "bundle.verification_artifacts");
  expectObject(bundle.json, "handoff_artifacts", errors, "bundle.handoff_artifacts");
  expectObject(bundle.json, "suggested_commands", errors, "bundle.suggested_commands");
  const bundleFields = expectArray(bundle.json, "handoff_fields", errors, "bundle.handoff_fields");
  if (bundleFields && bundleFields.length === 0) {
    errors.push(`bundle.handoff_fields must not be empty`);
  }

  if (request) {
    const contractValidation = validateProvisioningRequestContract(request.json);
    if (!contractValidation.ok) {
      errors.push(`request contract validation failed: ${contractValidation.errors.join("; ")}`);
    }
    if (request.json.tenant?.tenant_id !== bundle.json.tenant_id) {
      errors.push(`request.tenant.tenant_id must match bundle.tenant_id`);
    }
    if (request.json.tenant?.deploy_env !== bundle.json.deploy_env) {
      errors.push(`request.tenant.deploy_env must match bundle.deploy_env`);
    }
    if (request.json.tenant?.base_url !== bundle.json.base_url) {
      errors.push(`request.tenant.base_url must match bundle.base_url`);
    }
  }

  if (submission) {
    expectBoolean(submission.json, "ok", errors, "submission.ok");
    if (!isIsoTimestamp(submission.json.submitted_at)) {
      errors.push(`submission.submitted_at must be an ISO timestamp`);
    }
    expectBoolean(submission.json, "dry_run", errors, "submission.dry_run");
    const retry = expectObject(submission.json, "retry", errors, "submission.retry");
    if (retry) {
      expectNumber(retry, "retries", errors, "submission.retry.retries");
      expectNumber(retry, "retry_backoff_ms", errors, "submission.retry.retry_backoff_ms");
      const retryOn = expectArray(retry, "retry_on", errors, "submission.retry.retry_on");
      if (retryOn && retryOn.some((value) => typeof value !== "number")) {
        errors.push(`submission.retry.retry_on must contain only numbers`);
      }
      const attempts = expectArray(retry, "attempts", errors, "submission.retry.attempts");
      if (attempts) {
        attempts.forEach((attempt, index) => {
          if (!isObject(attempt)) {
            errors.push(`submission.retry.attempts[${index}] must be an object`);
            return;
          }
          expectNumber(attempt, "attempt", errors, `submission.retry.attempts[${index}].attempt`);
          if (!isIsoTimestamp(attempt.started_at)) {
            errors.push(`submission.retry.attempts[${index}].started_at must be an ISO timestamp`);
          }
          if (!isIsoTimestamp(attempt.completed_at)) {
            errors.push(`submission.retry.attempts[${index}].completed_at must be an ISO timestamp`);
          }
          expectNumber(attempt, "duration_ms", errors, `submission.retry.attempts[${index}].duration_ms`);
          expectBoolean(attempt, "ok", errors, `submission.retry.attempts[${index}].ok`);
          expectBoolean(attempt, "retryable", errors, `submission.retry.attempts[${index}].retryable`);
          expectNullableString(attempt.error ?? null, errors, `submission.retry.attempts[${index}].error`);
          if (attempt.status !== null && attempt.status !== undefined && typeof attempt.status !== "number") {
            errors.push(`submission.retry.attempts[${index}].status must be null/undefined or a number`);
          }
          expectNullableString(attempt.status_text ?? null, errors, `submission.retry.attempts[${index}].status_text`);
        });
      }
    }
    const submissionRequest = expectObject(submission.json, "request", errors, "submission.request");
    if (submissionRequest) {
      expectString(submissionRequest, "path", errors, "submission.request.path");
      expectString(submissionRequest, "sha256", errors, "submission.request.sha256");
      const metadata = expectObject(submissionRequest, "metadata", errors, "submission.request.metadata");
      if (request && submissionRequest.path !== request.path) {
        errors.push(`submission.request.path must match --request`);
      }
      if (request && submissionRequest.sha256 !== sha256(request.raw)) {
        errors.push(`submission.request.sha256 must match --request content`);
      }
      if (metadata && request && metadata.tenant_id !== request.json.tenant?.tenant_id) {
        errors.push(`submission.request.metadata.tenant_id must match request.tenant.tenant_id`);
      }
    }
  }

  if (applyEvidence) {
    expectBoolean(applyEvidence.json, "ok", errors, "apply.ok");
    if (!["dry-run", "write"].includes(applyEvidence.json.mode)) {
      errors.push(`apply.mode must be dry-run or write`);
    }
    expectString(applyEvidence.json, "base_url", errors, "apply.base_url");
    expectString(applyEvidence.json, "tenant_id", errors, "apply.tenant_id");
    if (!isIsoTimestamp(applyEvidence.json.started_at)) {
      errors.push(`apply.started_at must be an ISO timestamp`);
    }
    if (!isIsoTimestamp(applyEvidence.json.completed_at)) {
      errors.push(`apply.completed_at must be an ISO timestamp`);
    }
    expectNumber(applyEvidence.json, "duration_ms", errors, "apply.duration_ms");
    expectObject(applyEvidence.json, "summary", errors, "apply.summary");
    const actionResults = expectArray(applyEvidence.json, "action_results", errors, "apply.action_results");
    if (actionResults && actionResults.length === 0) {
      errors.push(`apply.action_results must not be empty`);
    }
    const applyErrors = expectArray(applyEvidence.json, "errors", errors, "apply.errors");
    if (applyErrors && applyErrors.some((item) => !isObject(item))) {
      errors.push(`apply.errors must contain only objects`);
    }
    if (request && applyEvidence.json.request_path !== request.path) {
      errors.push(`apply.request_path must match --request`);
    }
  }

  if (verify) {
    expectBoolean(verify.json, "ok", errors, "verify.ok");
    if (!isIsoTimestamp(verify.json.started_at)) {
      errors.push(`verify.started_at must be an ISO timestamp`);
    }
    if (!isIsoTimestamp(verify.json.completed_at)) {
      errors.push(`verify.completed_at must be an ISO timestamp`);
    }
    expectNumber(verify.json, "duration_ms", errors, "verify.duration_ms");
    expectNumber(verify.json, "check_count", errors, "verify.check_count");
    const checks = expectArray(verify.json, "checks", errors, "verify.checks");
    if (checks && checks.length === 0) {
      errors.push(`verify.checks must not be empty`);
    }
  }

  if (state.json.ok !== true) {
    errors.push(`state.ok must be true`);
  }
  if (state.json.schema_version !== "2026-04-01") {
    errors.push(`state.schema_version must be 2026-04-01`);
  }
  if (!isIsoTimestamp(state.json.generated_at)) {
    errors.push(`state.generated_at must be an ISO timestamp`);
  }

  const handoffState = expectObject(state.json, "handoff_state", errors, "state.handoff_state");
  if (handoffState) {
    if (!["draft", "ready_for_submission", "submitted", "applied", "verified"].includes(handoffState.status)) {
      errors.push(`state.handoff_state.status must be one of draft, ready_for_submission, submitted, applied, verified`);
    }
    if (!isIsoTimestamp(handoffState.updated_at)) {
      errors.push(`state.handoff_state.updated_at must be an ISO timestamp`);
    }
    const updatedFrom = expectObject(handoffState, "updated_from", errors, "state.handoff_state.updated_from");
    if (updatedFrom) {
      if (updatedFrom.bundle !== bundle.path) {
        errors.push(`state.handoff_state.updated_from.bundle must match --bundle`);
      }
      if ((updatedFrom.request ?? null) !== (request?.path ?? null)) {
        errors.push(`state.handoff_state.updated_from.request must match --request`);
      }
      if ((updatedFrom.submission ?? null) !== (submission?.path ?? null)) {
        errors.push(`state.handoff_state.updated_from.submission must match --submission`);
      }
      if ((updatedFrom.apply_evidence ?? null) !== (applyEvidence?.path ?? null)) {
        errors.push(`state.handoff_state.updated_from.apply_evidence must match --apply-evidence`);
      }
      if ((updatedFrom.verify ?? null) !== (verify?.path ?? null)) {
        errors.push(`state.handoff_state.updated_from.verify must match --verify`);
      }
    }
    expectNullableString(handoffState.previous_status ?? null, errors, "state.handoff_state.previous_status");
  }

  const expectedBundleSummary = summarizeBundle(bundle.json, bundle.path);
  compareValue(state.json.bundle, expectedBundleSummary, errors, "state.bundle");
  compareValue(state.json.request, request ? summarizeRequest(request) : null, errors, "state.request");
  compareValue(state.json.submission, submission ? summarizeSubmission(submission) : null, errors, "state.submission");
  compareValue(state.json.apply, applyEvidence ? summarizeApply(applyEvidence) : null, errors, "state.apply");
  compareValue(state.json.verify, verify ? summarizeVerify(verify) : null, errors, "state.verify");

  const evidence = expectObject(state.json, "evidence", errors, "state.evidence");
  if (evidence) {
    if (evidence.bundle_path !== bundle.path) {
      errors.push(`state.evidence.bundle_path must match --bundle`);
    }
    if (evidence.bundle_sha256 !== sha256(bundle.raw)) {
      errors.push(`state.evidence.bundle_sha256 must match --bundle content`);
    }
    if ((evidence.request_path ?? null) !== (request?.path ?? null)) {
      errors.push(`state.evidence.request_path must match --request`);
    }
    if ((evidence.request_sha256 ?? null) !== (request ? sha256(request.raw) : null)) {
      errors.push(`state.evidence.request_sha256 must match --request content`);
    }
    if ((evidence.submission_path ?? null) !== (submission?.path ?? null)) {
      errors.push(`state.evidence.submission_path must match --submission`);
    }
    if ((evidence.submission_sha256 ?? null) !== (submission ? sha256(submission.raw) : null)) {
      errors.push(`state.evidence.submission_sha256 must match --submission content`);
    }
    if ((evidence.apply_evidence_path ?? null) !== (applyEvidence?.path ?? null)) {
      errors.push(`state.evidence.apply_evidence_path must match --apply-evidence`);
    }
    if ((evidence.apply_evidence_sha256 ?? null) !== (applyEvidence ? sha256(applyEvidence.raw) : null)) {
      errors.push(`state.evidence.apply_evidence_sha256 must match --apply-evidence content`);
    }
    if ((evidence.verify_path ?? null) !== (verify?.path ?? null)) {
      errors.push(`state.evidence.verify_path must match --verify`);
    }
    if ((evidence.verify_sha256 ?? null) !== (verify ? sha256(verify.raw) : null)) {
      errors.push(`state.evidence.verify_sha256 must match --verify content`);
    }
  }

  const nextActions = expectArray(state.json, "next_actions", errors, "state.next_actions");
  if (nextActions && nextActions.some((item) => typeof item !== "string")) {
    errors.push(`state.next_actions must contain only strings`);
  }

  if (errors.length > 0) {
    throw new Error(`Tenant handoff evidence validation failed:\n- ${errors.join("\n- ")}`);
  }

  process.stdout.write(
    `${JSON.stringify(
      {
        ok: true,
        bundle_path: bundle.path,
        state_path: state.path,
        tenant_id: bundle.json.tenant_id,
        deploy_env: bundle.json.deploy_env,
      },
      null,
      2,
    )}\n`,
  );
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : String(error));
  process.exit(1);
});
